### ISSUE TITLE
Bug with areas

### ISSUE THREAD

**Issue by Edward17** [MapBBCode/mapbbcode#58]
Since some days I have a problem with the areas (polygons) in MapBBcode Share. These steps cause a problem:

1. Create an area.
2. Click "Export", choose "GPX", save file
3. Open new tab with MapBBcode Share
4. Click "Import", choose just saved file
5. We see not a polygon, but a non-closed line. A section between first and last node of polygon is missing.

P. S. Sorry for my bad English.

**Comment by Zverik** [comment]
I wonder why did I deliberately made them unclosed.
Should be fixed now.

**Comment by Edward17** [comment]
@Zverik thanks you, now all is working right.
